# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    dir
    powershell -Command "Invoke-WebRequest https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%204.9%20series/4.9.2-tdm-1%20DW2/gcc-4.9.2-tdm-1-dw2-c%2B%2B.zip/download -OutFile tdm_gcc.zip"
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: 'tdm_gcc.zip'
        destinationFolder: 'tdm_gcc'
        cleanDestinationFolder: true
        overwriteExistingFiles: true
    cd tdm_gcc
    cd bin
    # g++dw2.exe "" -o "" -march=native -mmmx -Ofast -m64 -std=c++14 -static -lcomdlg32 -luuid -m64
  displayName: 'windows-build'
