# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'windows-latest'

name: "build-check"

steps:
- script: |
    dir
    pip3 install wget
    python download_boost_fast.py
    7z x -y boost.zip
    move boost_1_76_0\boost boost
    dir
    g++ SAFOR.cpp -o SAFOR64.exe -DREMSUST=false -march=native -mmmx -Ofast -m64 -std=c++17 -I"." -static -lcomdlg32 -luuid -m64 -s
    g++ SAFOR.cpp -o SAFOR32.exe -DREMSUST=false -march=native -mmmx -Ofast -m32 -std=c++17 -I"." -static -lcomdlg32 -luuid -m32 -s
    g++ SAFOR.cpp -o SAFSOR.exe -DREMSUST=true -march=native -mmmx -Ofast -m64 -std=c++17 -I"." -static -lcomdlg32 -luuid -m64 -s
    g++ SAFOR.cpp -o SAFAR.exe -DVELOCITYTHRESHOLDFLAG -march=native -mmmx -Ofast -m64 -std=c++17 -I"." -static -lcomdlg32 -luuid -m64 -s
    mkdir SAFR 
    move SAFOR64.exe SAFR/SAFOR64.exe
    move SAFOR32.exe SAFR/SAFOR32.exe
    move SAFSOR.exe SAFR/SAFSOR.exe
    move SAFAR.exe SAFR/SAFAR.exe
  displayName: 'windows-build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'SAFR'
    artifactName: SAFORs