name: SAFOR

on:
  push:
    branches: 
      - master
      - develop
      - develop-*
  pull_request:
    branches: 
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: 'windows-2019'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          dir C:\ProgramData\Chocolatey
          C:\ProgramData\Chocolatey\bin\windres.exe --input SAFOR32.rc --output SAFOR32.res --output-format=coff --target pe-i386
          C:\ProgramData\Chocolatey\bin\windres.exe --input SAFOR64.rc --output SAFOR64.res --output-format=coff --target pe-x86-64
          C:\ProgramData\Chocolatey\bin\g++ SAFOR.cpp -o SAFOR64.exe SAFOR64.res -msse2 -Ofast -m64 -std=c++17 -I"." -static -lgdi32 -lcomdlg32 -luuid -luxtheme -lcomctl32 -s
      - name: Upload preps
        run: |
          dir
          mkdir SAFOR 
          move SAFOR64.exe SAFOR/SAFOR64.exe

      - uses: actions/upload-artifact@v2
        name: Upload
        with: 
          name: SAFOR
          path: SAFOR
